// <auto-generated />
using System;
using DuQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuQ.Migrations
{
    [DbContext(typeof(DuqContext))]
    partial class DuqContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DuQ.Data.DuQueue", b =>
                {
                    b.Property<long>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QueueStatusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QueueTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("QueueId");

                    b.HasIndex("QueueStatusId");

                    b.HasIndex("QueueTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("DuQueues");
                });

            modelBuilder.Entity("DuQ.Data.DuQueueStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DuQueueStatuses");
                });

            modelBuilder.Entity("DuQ.Data.DuQueueType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DuQueueTypes");
                });

            modelBuilder.Entity("DuQ.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DuQ.Data.DuQueue", b =>
                {
                    b.HasOne("DuQ.Data.DuQueueStatus", "QueueStatus")
                        .WithMany("Queues")
                        .HasForeignKey("QueueStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuQ.Data.DuQueueType", "QueueType")
                        .WithMany("Queues")
                        .HasForeignKey("QueueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuQ.Data.Student", "Student")
                        .WithMany("Queues")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueStatus");

                    b.Navigation("QueueType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DuQ.Data.DuQueueStatus", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("DuQ.Data.DuQueueType", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("DuQ.Data.Student", b =>
                {
                    b.Navigation("Queues");
                });
#pragma warning restore 612, 618
        }
    }
}
